apiVersion: v1
kind: Service
metadata:
  name: html-service
  namespace: dulina
spec:
  type: NodePort
  selector:
    app: html-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80       # Container Port
      nodePort: 30200      # Access via NodeIP:30200
